apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis 
  labels:
    name: redis
    app: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: gcr.io/google_containers/redis
        ports:
        - containerPort: 6379         
          protocol: TCP