apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web
    spec:       
      containers:
      - name: web
        image: asia.gcr.io/samirh-sandbox/web-python:v2
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP